### ISSUE TITLE
Update package json to latest and stable engine versions

### ISSUE THREAD

**Issue by interc0der** [XRPL-Labs/Xumm-Universal-SDK#1]
Is there a reason why this package is not compatible with the latest version of node and npm?

**Comment by WietseWind** [comment]
It should be, what are you encountering?

**Comment by interc0der** [comment]
It looks like the most current version of Node is 19.4.0 for all devices.
https://nodejs.org/en/download/current/

If you try installing the package on a machine running the most current version of Node, you will get an error during installation.

**Comment by WietseWind** [comment]
I just installed successfully. I did not get any errors. I did get the warning about the node version compatibility though, but not an error: I managed to npm install, build, etc. without problems.

Is this (what I encountered, not an error but a notification) what you refer to, or do you encounter an actual error (and if so: which one?)

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/4756161/213314962-09623446-9b33-4328-86d1-598405ac7b00.png">
