### ISSUE TITLE
Asyncify is not resolved/rejected when not signed in.

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/Xumm-Universal-SDK#2]
Promise (Asyncify) fields such as UnifiedUserData.account are in a pending state if the user is not signed in.

In the pending state, it is not possible to determine whether the user is not signed in or whether the user data is being loaded.

**Comment by WietseWind** [comment]
That's as designed: when the account is unknown, it is unknown. It is just pending until it resolves, when the account is known. 

To determine the state of the sign in process, an actual data property is not the way to find it: that is either not yet there, or the full cycle is completed and the data is there.

Can you elaborate on the user flow? Are you looking to build an indicator that either mentions:
- Not logged in [Sign in] (button)
- Signing in...
- Signed in: account: ...

Or is it something else?

**Comment by develoQ** [comment]
There is no problem during the sign-in process.

The problem is when the browser is reloaded after signing in.

If the sign-in status is only determined by whether the user information has been resolved, the flow is as follows
reload→not logged in→(resolve)→signed in
(This causes UI flickering in the browser.)

The flow I want is
reload→(loading)→(resolve)→signed in

**Comment by WietseWind** [comment]
Perfect, I understand. I'll add a property to detect this :)

**Comment by WietseWind** [comment]
Un the SDK today based on your input: two new events:

- `retrieving` to indicate that it's retrieving the state of an existing sign in (JWT flow)
- `ready` to indicate that everything is ready: retrieving a potential sign in, signing the user in, etc. (or not, in which case it's still ready but then you'll know you have to sign in the user first)

**Comment by develoQ** [comment]
The 'ready' event is not executed when the browser and unsigned in.

The 'ready' event requires all readyPromises to be resolved.
In the case of the browser, the 'success' or 'retrieved' event must be executed because the readyPromises contain the following code parts

https://github.com/XRPL-Labs/Xumm-Universal-SDK/blob/af8a05f04a562a0ece08d666d2df841ce907bc45/src/index.ts#L537-L548

The 'ready' event should be executed even if the 'success' or 'retrieved' event is not executed.

**Comment by WietseWind** [comment]
Thank you! Nice catch.

Fixed & deployed as `v1.1.11`

**Comment by develoQ** [comment]
If the Promise of pkceRetrieverResolver is present, 

It should be processed in the order of success→ready, but it is processed in the order of ready→success.

In the sign-in state
(load) → success → ready

In the non-sign-in state
(load) → ready

The flow of "ready" is considered to be appropriate.

It may be difficult because there does not seem to be a process to reject in the Promise process at present.

**Comment by WietseWind** [comment]
That's not how I designed it; "ready" means that the SDK is ready potentially picking up on existing sign in state, it doesn't mean the actual sign in is ready.

So: 
(load) » retrieving » ready (with potential retrieving)

Is the proposed different order required, or a nice to have?

**Comment by develoQ** [comment]
I don't think it is required, but it is necessary to eliminate component flickering on reload.
(Also for future developers).

It would be great if this could be addressed in future updates.

**Comment by WietseWind** [comment]
Clear, makes sense. Thanks. I'll add it ASAP.

**Comment by WietseWind** [comment]
Fixed in `v1.1.12`

With:
- https://github.com/XRPL-Labs/XummPkce/commit/cad4f2d91fd9397ddffeec9b41a4e083bf243b09
- https://github.com/XRPL-Labs/Xumm-Universal-SDK/commit/62a9061310f551d87aa3cbaec4e29562cd6561a0

**Comment by develoQ** [comment]
Thank you for your response!

I ran the sample html and it seems that the 'ready' event is not working when the browser (b-flow) is not signed in.

This is because "loggedout" is emitted in the XummPKCE constructor process, 

https://github.com/XRPL-Labs/XummPkce/blob/1231580ed1dd80f5ca8408e952e57e05bd527974/src/index.ts#L183

https://github.com/XRPL-Labs/XummPkce/blob/1231580ed1dd80f5ca8408e952e57e05bd527974/src/index.ts#L497


and, it seems that the emit is done before the "loggedout" event is detected at this point.

https://github.com/XRPL-Labs/Xumm-Universal-SDK/blob/932a393e991d32e91eee7e6de95dc5171f077177/src/index.ts#L681


The original emit should be `on("loggedout",***)→this.emit("loggedout")`, but here I think it's the other way round.

**Comment by WietseWind** [comment]
@develoQ I tested this thoroughly, both flows. Also in browser and non-signed in flow, this works for me.

I don't understand what you mean with the last part of your message. It's the PKCE class that emits the loggedout event, also if there's nothing to log in (so the state is, indeed, loggedout). 

It's the Universal SDK picking up on that to resolve to ready.

**Comment by develoQ** [comment]
Oh, I'm sorry.
It was an error on our part.

The sample code is working correctly.

**Comment by WietseWind** [comment]
Awesome, super happy to hear that.

You did identify the event being sent in the constructor flow. While in this case the logout method is in the next event loop, just to make sure it won't cause any future trouble I just published universal SDK `v1.1.13` based on PKCE lib `v2.7.5` forcing the event to the next tick with a setTimeout 0; https://github.com/XRPL-Labs/XummPkce/commit/6f04d9843adf4c56cf50e62f2bec803f263a0fca
