### ISSUE TITLE
Use XummSdkJwt when CLI and JWT?

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/Xumm-Universal-SDK#3]
I think XummSdkJwt should be used when using CLI and OAuth2 flow jwt, what do you think?

https://github.com/XRPL-Labs/Xumm-Universal-SDK/blob/b2a2d00c51d32a13f7832aac0be2989a100b8ba1/src/index.ts#L530-L537

**Comment by WietseWind** [comment]
There is no CLI+OAuth2 flow,

If CLI: key + secret = `XummSdk`

If OAuth2: key + JWT flow = `XummSdkJwt `

**Comment by develoQ** [comment]
How is it appropriate to use the signed-in user's information on the server side (CLI) after signing in with the PKCE OAuth flow (XummPkce.authorise())?

I am not familiar with this😫

**Comment by WietseWind** [comment]
Can you explain the flow, and define users signed in information?

Do you mean: you obtain a JWT on the frontend, pass that to your backend and let your backend interact with our platform from the user context?

**Comment by develoQ** [comment]
Yes, it would be nice to be able to retrieve data from the backend.

In my current environment, I didn't need to create a Payload with user_token, I just wanted to be able to convert the user's JWT to a user Object.

Other libraries can be used to encode JWTs, but I felt it would be best if the Xumm SDK alone could encode them (with type definitions).

**Comment by WietseWind** [comment]
Which data exactly? And retrieve how? Can you specify the flow? 

Do you mean: you obtain a JWT on the frontend, pass that to your backend and let your backend? Or something else?

I don't think I quite understand. The JWT is an access token. Do you mean the `me` profile data you can fetch with this NFT? Because that is fully typed?

**Comment by develoQ** [comment]
I am trying to store the JWT into a cookie and check the user on the server side (e.g. check for NFT possession).

The flow is as follows.
1. SIgnIn (XummPKCE) → get JWT(from bearer field) → send JWT to backend → save to Cookie
2. page access → get cookie from backend → decode JWT → check NFT etc. from address → redirect etc. depending on results
